// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALH7795xvCu8i375cuR1uGfMiGaF3_Fk4',
    appId: '1:1010786257076:android:d39b802d38294e5d426fe1',
    messagingSenderId: '1010786257076',
    projectId: 'chahele-learning-app',
    storageBucket: 'chahele-learning-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLCUvBGhji8iRyOxjSUyUuF2os45hMnU',
    appId: '1:1010786257076:ios:cadcfaa8372fc6ef426fe1',
    messagingSenderId: '1010786257076',
    projectId: 'chahele-learning-app',
    storageBucket: 'chahele-learning-app.appspot.com',
    androidClientId: '1010786257076-1ub23qq92p5mbncr0m9h51889i571tkm.apps.googleusercontent.com',
    iosClientId: '1010786257076-3bed84gfq2o2usl5b9af6u7htqja174o.apps.googleusercontent.com',
    iosBundleId: 'com.chahel.elearning',
  );

}